### PR TITLE
Update Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by BreakshadowCN**
Simplified Chinese (简体中文) translation updated.

### CODE REVIEW

**Review by Windows200000 — COMMENTED** [review]
I can't check this beyond ChatGPT, but it seems alright, thanks!

**Comment by Windows200000** [comment]
Could you please also edit the README.md file for credits and patch_notes.txt to include the changes? This wasn't in my original message until now, but doing it separately could become a hassle and it would unnecessarily clutter commits.

**Review by Windows200000 — CHANGES_REQUESTED** [review]
@BreakshadowCN Could you please also edit the README.md file for credits and patch_notes.txt to include the changes? This wasn't in my original message until now, but doing it separately could become a hassle and it would unnecessarily clutter commits.

**Comment by Windows200000** [comment]
I did it myself, it was easier for now, sorry for pinging.

**Comment by BreakshadowCN** [comment]
Thank you for accepting this patch!
I've already directed some Chinese people who does not know how to use Github to this new fork to solve their issue while DevilXD has to solve irl things and can't audit the PR/do a rewrite of TDM.

**Pull request merged**
