### PR TITLE
Unlinked campaigns & Console logs

### PR DESCRIPTION
**Pull request by Valentin-Metz**
This is the non-draft pull request for #66 (different base branch; that's why it's a new pull request).
Every change is its own commit, so it can be reverted at a later stage without effort if desired.

### CODE REVIEW

**Comment by Windows200000** [comment]
@Valentin-Metz As I described in the original, I've decided against unlinked campaigns for now.

I would have to test the effects of the var name change in GitLocalize, as I have experienced pemding translation loss when changing the files manually, if important to you.

I am kind of indifferent towards the logs.

Is there anything else that would make maintaining your fork easier?

**Comment by Valentin-Metz** [comment]
That should be enough for now, if anything else comes up, I'll create a new pull request for that :+1:.

**Comment by Windows200000** [comment]
@Valentin-Metz 

I was testing whether everything in the new release works on linux and realized that this log doesn't respect translation.
```
self._manager.print(f"Progress: {self._drop.current_minutes}/{self._drop.required_minutes} - {self._drop.campaign}")
```

Just a heads up, that this has been changed in https://github.com/Windows200000/TwitchDropsMiner-updated/commit/9731bccf22a0ac4b36fef56b76f4eea76e33ced9.

**Comment by Valentin-Metz** [comment]
> I was testing whether everything in the new release works on linux and realized that this log doesn't respect translation.
While this is one way of doing this, consider that there is some utility in not translating these. Mainly that you can ask any person for their console logs and you'll get comparable, searchable and immediately dev-readable log. The user orientated log in the UI is always translated.

**Pull request merged**
